Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  # Enable USB passthrough for our USB stick.
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["modifyvm", :id, "--usbehci", "on"]
    vb.customize ["usbfilter", "add", "0",
      "--target", :id,
      "--name", "USB stick",
      "--vendorid", "0x26bd",
      "--productid", "0x9917"]
  end
end
